import type { Metadata } from 'next';
import { Inter, Raleway } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import { cn } from '@/lib/utils';
import Providers from '@/providers';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });
const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' });

export const metadata: Metadata = {
	title: 'Sathish - Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={cn(raleway.className, 'flex flex-col min-h-screen')}>
				<Providers
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<Header />
					{children}
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
