import Footer from '@/components/footer';
import Header from '@/components/header';
import NavBar from '@/components/nav-bar';
import { MobileDrawer } from '@/components/nav-drawer';
import { cn } from '@/lib/utils';
import Providers from '@/providers';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import { Bounce, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';

const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' });

export const metadata: Metadata = {
	title: 'Sathish - Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={cn(
					raleway.className,
					'flex flex-col min-h-screen overflow-x-clip'
				)}>
				<Providers
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<Header />
					<NavBar />
					<MobileDrawer />
					{children}
					<Footer />
					<ToastContainer
						position='top-center'
						autoClose={2000}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick
						rtl={false}
						pauseOnFocusLoss
						draggable
						pauseOnHover
						theme='colored'
						transition={Bounce}
					/>
					<SpeedInsights />
				</Providers>
			</body>
		</html>
	);
}
